# Generated by Django 3.2.5 on 2021-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abil_name', models.CharField(max_length=50)),
                ('abil_type', models.CharField(max_length=50)),
                ('abil_damage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=50)),
                ('char_class', models.CharField(max_length=50)),
                ('char_race', models.CharField(max_length=50)),
                ('abilities', models.ManyToManyField(to='char_col.Ability')),
            ],
        ),
    ]
