# Generated by Django 3.2.5 on 2021-07-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_col', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='campaign date')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('P', 'In Progress'), ('C', 'Completed')], default='S', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_col.character')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
