# Generated by Django 3.2.5 on 2021-07-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_col', '0002_campaigns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
    ]
